"""Removed profiles from sessions

Revision ID: 2b8f48c92f86
Revises: 3a3d2a89b7fe
Create Date: 2020-03-23 22:21:33.169930

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b8f48c92f86'
down_revision = '3a3d2a89b7fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sessions_ibfk_1', 'sessions', type_='foreignkey')
    op.drop_column('sessions', 'profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('profile_id', mysql.VARCHAR(length=255), nullable=True))
    op.create_foreign_key('sessions_ibfk_1', 'sessions', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###
