"""Added products foreign to orders

Revision ID: 3a3d2a89b7fe
Revises: e0c36c50487a
Create Date: 2020-03-23 22:19:36.608220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3d2a89b7fe'
down_revision = 'e0c36c50487a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('product_id', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'product_id')
    # ### end Alembic commands ###
