"""Testing foreignkeys

Revision ID: 8c49969fa6bf
Revises: 20e346cb546a
Create Date: 2020-03-11 19:07:55.544645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c49969fa6bf'
down_revision = '20e346cb546a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buids', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.add_column('buids', sa.Column('session_id', sa.Integer(), nullable=True))
    op.drop_constraint('buids_ibfk_1', 'buids', type_='foreignkey')
    op.create_foreign_key(None, 'buids', 'profiles', ['profile_id'], ['id_pk'])
    op.create_foreign_key(None, 'buids', 'sessions', ['session_id'], ['id_pk'])
    op.drop_column('buids', 'parent_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buids', sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buids', type_='foreignkey')
    op.drop_constraint(None, 'buids', type_='foreignkey')
    op.create_foreign_key('buids_ibfk_1', 'buids', 'sessions', ['parent_id'], ['id_pk'])
    op.drop_column('buids', 'session_id')
    op.drop_column('buids', 'profile_id')
    # ### end Alembic commands ###
