"""Testing

Revision ID: c07eca73935e
Revises: 2b8f48c92f86
Create Date: 2020-03-24 11:07:38.788317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07eca73935e'
down_revision = '2b8f48c92f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
