"""Rebuilding tables

Revision ID: e0c36c50487a
Revises: 30f233eab73b
Create Date: 2020-03-23 22:18:34.697414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0c36c50487a'
down_revision = '30f233eab73b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('sub_category', sa.String(length=255), nullable=True),
    sa.Column('sub_sub_category', sa.String(length=255), nullable=True),
    sa.Column('sub_sub_sub_category', sa.String(length=255), nullable=True),
    sa.Column('recommandable', sa.Boolean(), nullable=True),
    sa.Column('online_only', sa.Boolean(), nullable=True),
    sa.Column('target_demographic', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=90), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    sa.Column('odor_type', sa.String(length=255), nullable=True),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=255), nullable=True),
    sa.Column('variant', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('type_of_hair_care', sa.String(length=255), nullable=True),
    sa.Column('type_of_hair_coloring', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('first_order', sa.DateTime(), nullable=True),
    sa.Column('latest_order', sa.DateTime(), nullable=True),
    sa.Column('order_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.Column('session_start', sa.DateTime(), nullable=True),
    sa.Column('session_end', sa.DateTime(), nullable=True),
    sa.Column('browser_name', sa.String(length=255), nullable=True),
    sa.Column('os_name', sa.String(length=255), nullable=True),
    sa.Column('is_mobile_flag', sa.Boolean(), nullable=True),
    sa.Column('is_pc_flag', sa.Boolean(), nullable=True),
    sa.Column('is_tablet_flag', sa.Boolean(), nullable=True),
    sa.Column('is_email_flag', sa.Boolean(), nullable=True),
    sa.Column('device_family', sa.String(length=255), nullable=True),
    sa.Column('device_brand', sa.String(length=255), nullable=True),
    sa.Column('device_model', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommended_before',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('profile_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_Id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_Id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders_products')
    op.drop_table('orders')
    op.drop_table('buids')
    op.drop_table('recommended_before')
    op.drop_table('sessions')
    op.drop_table('profiles')
    op.drop_table('products')
    # ### end Alembic commands ###
